# Base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose the port used by the WebSocketGateway
EXPOSE 80

# Start the server
CMD ["npm", "start"]
